version: '3'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: readme.so
    restart: always
    ports:
      - '8785:3000'
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
